### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by timvahlbrock** [shackijj/widget-typescript#5]
The dependency preact and the peer dependency preact-compat currently collide. preact-compat requires preact@<10.

**Comment by timvahlbrock** [comment]
Might be resolved by https://github.com/preactjs-templates/widget-typescript/pull/4

**Comment by omanikhi** [comment]
This is still an issue on v3.2.2 with several dependencies failing to resolve including preact-compat and sass-loader:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-modules@0.1.0
npm ERR! Found: preact@10.5.14
npm ERR! node_modules/preact
npm ERR!   preact@"^10.3.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer preact@"<10" from preact-compat@3.19.0
npm ERR! node_modules/preact-compat
npm ERR!   preact-compat@"^3.17.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

✖ ERROR Error: Exited with status 1
    at closeArgsToError (/Users/me/.npm/_npx/832725a7f7f8e372/node_modules/cross-spawn-promise/lib/index.js:20:16)
    at ChildProcess.<anonymous> (/Users/me/.npm/_npx/832725a7f7f8e372/node_modules/cross-spawn-promise/lib/index.js:76:19)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

After removing preact-compat altogether:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: preact-cli@3.2.2
npm ERR! Found: sass-loader@6.0.7
npm ERR! node_modules/sass-loader
npm ERR!   dev sass-loader@"^6.0.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional sass-loader@"^10.2.0" from preact-cli@3.2.2
npm ERR! node_modules/preact-cli
npm ERR!   dev preact-cli@"^3.0.0-next.19" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: sass-loader@10.2.0
npm ERR! node_modules/sass-loader
npm ERR!   peerOptional sass-loader@"^10.2.0" from preact-cli@3.2.2
npm ERR!   node_modules/preact-cli
npm ERR!     dev preact-cli@"^3.0.0-next.19" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

**Comment by omanikhi** [comment]
So turns out, using Node 16 is an issue here. I switched to Node 14 as described in [this](https://stackoverflow.com/a/67242989/1038245) life-saving answer and the project resolved and compiled correctly.

**Comment by rschristian** [comment]
Should be corrected now, template no longer ships `sass` right out-of-the-box.
