### ISSUE TITLE
ForkTsChekerWebpackPlugin complains about unknown property "silent"

### ISSUE THREAD

**Issue by jusurb** [shackijj/widget-typescript#6]
```
$ preact watch --template src/template.html
✖ ERROR ValidationError: Invalid configuration object. ForkTsCheckerWebpackPlugin has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'silent'. These properties are valid:
   object { async?, typescript?, eslint?, formatter?, issue?, logger? }
    at Object.validate [as default] (widget-typescript/node_modules/fork-ts-checker-webpack-plugin/node_modules/schema-utils/dist/validate.js:96:11)
    at new ForkTsCheckerWebpackPlugin (widget-typescript/node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.js:31:31)
    at createBaseConfig (widget-typescript/node_modules/preact-cli/lib/lib/webpack/webpack-base-config.js:343:7)
    at createClientConfig (widget-typescript/node_modules/preact-cli/lib/lib/webpack/webpack-client-config.js:321:3)
    at devBuild (widget-typescript/node_modules/preact-cli/lib/lib/webpack/run-webpack.js:18:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Versions:

- preact-habitat@3.3.0
- preact-render-to-string@5.1.19
- preact@10.5.13

**Comment by rschristian** [comment]
Fixed in https://github.com/preactjs/preact-cli/pull/1567
